# Repeated to match gpu_variant zip_keys (none, cuda, cuda)
c_compiler:                      # [win]
  - vs2022                       # [win]
  - vs2022                       # [win]
  - vs2022                       # [win]
cxx_compiler:                    # [win]
  - vs2022                       # [win]
  - vs2022                       # [win]
  - vs2022                       # [win]

gpu_variant:
  - none
  - cuda                         # [linux or win]
  - cuda                         # [linux or win]

cuda_compiler:                   # [linux or win]
  - cuda-nvcc                    # [linux or win]

cuda_compiler_version:           # [linux or win]
  - none                         # [linux or win]
  - 12.9                         # [linux or win]
  - 13.1                         # [linux or win]

zip_keys:
  -
    - gpu_variant
    - cuda_compiler_version      # [linux or win]
    - c_compiler                 # [win]
    - cxx_compiler               # [win]
