{% set name = "lightgbm" %}
{% set version = "4.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e1cd7baf0318d4e308a26575a63a4635f08df866ad3622a9d8e3d71d9637a1ba
  patches:
    - boost_shared.diff

build:
  number: 1
  string: cuda_py{{ PY_VER }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version != "None"]
  string: cpu_py{{ PY_VER }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}  # [cuda_compiler_version == "None"]
  # CUDA is not supported in windows
  skip: true  # [cuda_compiler_version != "None" and win]
  script:
    - set "CMAKE_GENERATOR_PLATFORM="                 # [win]
    - set "CMAKE_GENERATOR_TOOLSET="                  # [win]
    - set CMAKE_GENERATOR=Ninja                       # [win]
    - set "CMAKE_ARGS=%CMAKE_ARGS% -DUSE_CUDA=1"      # [cuda_compiler_version != "None" and win]
    # For CPU builds, we include OpenCL too. USE_GPU means OpenCL and not CUDA builds
    - set "CMAKE_ARGS=%CMAKE_ARGS% -DUSE_GPU=1"       # [cuda_compiler_version == "None" and win]
    - export CMAKE_ARGS="${CMAKE_ARGS} -DUSE_CUDA=1"  # [cuda_compiler_version != "None" and not win]
    - export CMAKE_ARGS="${CMAKE_ARGS} -DUSE_GPU=1"   # [cuda_compiler_version == "None" and not win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cmake >=3.28
    - make    # [not win]
    - ninja   # [win]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
  host:
    - scikit-build-core >=0.9.3
    - python
    - pip
    - llvm-openmp  # [osx]
    - libgomp  # [linux]
    - libboost-devel              # [cuda_compiler_version == "None"]
    - ocl-icd                     # [cuda_compiler_version == "None" and linux]
    - khronos-opencl-icd-loader   # [cuda_compiler_version == "None" and not linux]
  run:
    - python
    - numpy >=1.17.0
    - scipy
    - __cuda                      # [cuda_compiler_version != "None"]
  # optional dependencies from [project.optional-dependencies]
  # at https://github.com/microsoft/LightGBM/blob/master/python-package/pyproject.toml
  run_constrained:
    - cffi >=1.15.1
    - dask >=2.0.0
    - pandas >=0.24.0
    - pyarrow >=6.0.1
    - scikit-learn !=0.22.0

test:
  imports:
    - lightgbm
  requires:
    - pip
    - scikit-learn
  commands:
    - pip check


about:
  home: https://github.com/microsoft/LightGBM
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: LightGBM is a gradient boosting framework that uses tree based learning algorithms.

  description: |
    A fast, distributed, high performance gradient boosting (GBDT, GBRT, GBM or MART) framework based on decision tree algorithms, used for ranking, classification and many other machine learning tasks.
  doc_url: https://lightgbm.readthedocs.io/en/stable/
  dev_url: https://github.com/microsoft/LightGBM

extra:
  recipe-maintainers:
    - synapticarbors
    - aldanor
    - xhochy
    - jameslamb
