travis:
  secure:
    BINSTAR_TOKEN: qMSL8L0upM4qSmQHVxW2CuqOTqHiu3mtVxnArFFkUfGGmB8GUn+FzVSfrn8kj7+QznQUnDfgWCIGz5Rsnccz03ZPCoLHxVpR9N8tzmxcVOJox0crUZjbijVLfTZUFjAWOL1uFobJomWSqDeoT2+0H9W7YWNRhQJIxv45E5BtJYOXHSWwMpSonHF9cErMthbJTK6ZoFuzh/fuUhgcND8KaiOCCd7/vSzPAiEuEBdSSh170RWOcgrvm0g0Ph+sxSZLeNin3xR1vq11T8doCWn+Nis5WhKUWaXYe/FM/o0ESKFh3l/tIZKF0WhYyGu5GXk3A6RNXSBbuUzh/WC9LuuLLx/xdGM9toTLZXBwTt5+s7Ue/KucJTorI/3+tJ1CbimTTc8u2g/IiCcBubjHwHgf0y0hu5LhqDpuzI9O38edFVfpnqK08K8S4JjU3eYJHy6QNaL4LCXpwmPQYEFh2WfpWG5qeL5TbzrFC282uXPYl7rXeugIMmAGuUVH0XP3FjfPHiJ4a+gkI9tJhIhhZHXFNWjU56pAvIo0Ch5PCwdDH+WPQkNxeuahxwxqe6b8XM6ubpOFltlep30KZoqnD7RCqhwkGQAsO7XT9wflcbQb9XRyB3ilz3WJP2/5bu/8oaFghr6xBEFxX85F9ynsJo7tHbNENrFCe8RykcTK3AsoiKM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
